### ISSUE TITLE
Identify how to support different deid strategy for each annotation type

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/nlp-sandbox-deidentifier#12]
## Deid strategies common to all annotation types

- Replace each character of the annotation by a character defined by the user (current implementation)
- Replace annotation content by a tag, e.g. "Thomas Schaffter" => "[ANNOTATION_TYPE]" where ANNOTATION_TYPE is replaced by a different identifier for each type of annotation, for example DATE, PERSON_NAME, etc.

The user of the API should be able to specify the deid strategy for each type of annotation that we support

## Task

Propose how we should change the current implementation to meet the above requirements

- Using one or more endpoints?
- Using query parameter or an object received as payload that contains the parameters?
- Format of the input and output

**Comment by tschaffter** [comment]
Done in https://github.com/Sage-Bionetworks/nlp-sandbox-schemas/pull/81

**Comment by cascadianblue** [comment]
This was [the proposal](https://lucid.app/lucidchart/670f484d-4a3f-42d8-bdcd-7aa34dce783e/edit?page=rbVNnJGW2urR#?folder_id=home&browser=icon) that went into the spec
